### ISSUE TITLE
data set creating issue

### ISSUE THREAD

**Issue by shanudhawale** [federico-terzi/gesture-keyboard#2]
TARGET SIGN: 'a' USING BATCH: 0
OPENING SERIAL_PORT 'COM9' WITH BAUDRATE 38400...
IMPORTANT!
To end the program hold Ctrl+C and send some data over serial
Traceback (most recent call last):
  File "start.py", line 118, in <module>
    ser = serial.Serial(SERIAL_PORT, BAUD_RATE, timeout = TIMEOUT)
  File "C:\Python27\lib\site-packages\serial\serialwin32.py", line 38, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\serial\serialutil.py", line 282, in __init__
    self.open()
  File "C:\Python27\lib\site-packages\serial\serialwin32.py", line 66, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM9': WindowsError(5, 'Access is denied.')

**Comment by federico-terzi** [comment]
Hi,

Are you sure you are using the correct serial port?
You can also try to execute the terminal with admin privileges and see if it works.
Sorry for the late reply, right now I'm very busy with my exams and I don't have much free time.

Have a nice day
