### ISSUE TITLE
serial port is not opening

### ISSUE THREAD

**Issue by Nadamohame** [federico-terzi/gesture-keyboard#28]
Opening serial port...
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\lib\site-packages\pygarl\__main__.py", line 129, in <module>
    cli()
  File "C:\Program Files\Python36\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python36\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Python36\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python36\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\pygarl\__main__.py", line 67, in sprint
    sprint_func(port=port, baudrate=baudrate)
  File "C:\Program Files\Python36\lib\site-packages\pygarl\plugins\sprint.py", line 15, in sprint
    line = line.replace("\n", "")
TypeError: a bytes-like object is required, not 'str'

**Comment by Nadamohame** [comment]
After typing python -m pygarl sprint -p myserialport 
this error is appearing how can I fix it please help
